CREATE TABLE ORDER_ITEMS (
    ID SERIAL PRIMARY KEY,

    ORDER_ID INTEGER,
    PRICE NUMERIC(15,2),
    PRODUCT_ID INTEGER,
    AMOUNT INTEGER,

    CONSTRAINT FK_ORDER_ITEM_ORDERS
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS (ID)
        ON DELETE CASCADE
    ,
    CONSTRAINT FK_ORDER_ITEM_PRODUCTS
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS (ID)
        ON DELETE CASCADE

);