spring:
  application:
    name: "CoffeeDays - API"
  datasource:
    url: jdbc:postgresql://localhost:5432/db-coffeedays
    username: user-coffeedays
    password: password

server:
  servlet:
    context-path: "/api"

coffee-days:
  token-secret-key: ${COFFEEDAYS_TOKEN_SECRET_KEY}